title: "内製ツール開発を支える IaC の重要性"
summary: |
  内製ツール開発現場における IaC (Infrastructure as Code) の立ち位置を整理し、その重要性について説明します (個人の考え含む)。
topics: ["IaC", "DevOps", "開発"]
published: true
price: 0
chapters:
  - 00_01_00-introduction
  - 00_02_00-development-pyramid
  - 00_03_00-example
  - 00_04_00-ideal-iac
  - 00_04_01-organizational-perspective
  - 00_05_00-upside-down-pyramid
