title: "内製ツール開発を支える IaC の重要性"
summary: "IaC の重要性を説明し、IaC が存在しないどのような崩壊が起こるのかを記述します。"
topics: ["IaC", "DevOps", "開発"]
published: true
price: 0
chapters:
  - 00_01_00-introduction
  - 00_02_00-development-pyramid
  - 00_03_00-example
  - 00_04_00-ideal-iac
  - 00_04_01-organizational-perspective
  - 00_05_00-upside-down-pyramid
